from numpy.polynomial import Chebyshev

xdata = [(2 / 11) * n - 1 for n in range(12)]
ydata = [440 * 2**((n + 116 - 69) / 12) for n in range(12)]
poly = Chebyshev.fit(xdata, ydata, 3)
coefs = ", ".join(map(str, poly.coef))
print("// AUTOGENERATED by build.rs from buildconsts.py")
print("// Edits will be overwritten!")
print()
print("/// Chebyshev series constants for top octave frequencies.")
print(f"pub const CHEBYSHEV_TOP_OCTAVE: [f32; 4] =\n    [{coefs}];")
