// AUTOGENERATED by build.rs from buildconsts.py
// Edits will be overwritten!

/// Chebyshev series constants for top octave frequencies.
pub const CHEBYSHEV_TOP_OCTAVE: [f32; 4] =
    [9361.596739618899, 2937.203518388179, 232.28608509908733, 12.275067234681403];
